services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: tail -f /dev/null
    volumes:
      - /home/dave/projects/Entity-Generator:/home/project/entity-generator
      - /home/project/entity-generator/node_modules
    ports:
      - '4210:4200'
